collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

exclude:
  - "*.config.js"
  - "Gemfile*"
  - "package*.json"
  - "README.md"
  - "yarn.lock"
  - "assets/css"
  - "assets/js"
  - "node_modules"

plugins:
  # from github pages (included for local dev)
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links
  # project specific
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag